# https://docs.microsoft.com/azure/devops/pipelines/languages/android
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Android/*

pool:
  vmImage: 'windows-2019'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: '$(system.defaultWorkingDirectory)/Android/gradlew'
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    tasks: 'assembleDebug'